### ISSUE TITLE
software question, closely related to nbrun, also posted in stackoverflow

### ISSUE THREAD

**Issue by rrtucci** [tritemio/nbrun#14]
Hi Antonino, I once asked in this forum a question about your wonderful nbrun, and you answered my question promptly, kindly, and very well. Now I have a question closely related to nbrun, that I suspect you could answer in your sleep, but  nobody at stackverflow has answered. Could you please take a look at  it
https://stackoverflow.com/questions/56829884/how-to-execute-cell-1-from-another-notebook-in-current-notebook

**Comment by rrtucci** [comment]
Answered my own question on Stackoverflow after help from an anonymous commenter.

**Comment by tritemio** [comment]
It was me ;-)

**Comment by rrtucci** [comment]
thanks, I suspected so
