### ISSUE TITLE
run the notebook with new instantiations rather than producing a new file

### ISSUE THREAD

**Issue by bikashg** [tritemio/nbrun#7]
Is there a way to execute the notebook with newly instantiated values (the arguments passed in) **directly** rather than producing a new copy of that notebook with the instantiated values?

**Comment by tritemio** [comment]
The notebook is executed "directly". You can just not save the notebook (ipynb file) after the execution using ` save_ipynb=False`.

**Comment by bikashg** [comment]
I did that; however the link to the default template keeps on appearing. But more importantly, I don't see any output from the template code ... seems like the call to the template is not executing any code on the template ??

**Comment by tritemio** [comment]
No output from the template notebook is ever shown in the master notebook. Normally you save the executed notebook either in ipynb or html to "see" the results. You can also save the results from multiple execution in a single CSV file and display that file as a table in the master notebook after the execution finishes. For an example see https://github.com/tritemio/multispot_paper/blob/master/index.ipynb
