### ISSUE TITLE
No output displayed from the code in the template notebook

### ISSUE THREAD

**Issue by bikashg** [tritemio/nbrun#8]
When executing the master notebook, I don't see any output printed from the code in the template notebook. Please see the attached screenshot.

![no_output](https://user-images.githubusercontent.com/17159812/41152687-574d7336-6b0c-11e8-97e4-975ba4f29b83.jpg)

**Comment by tritemio** [comment]
This looks like the normal output. Are you expecting to see results (tables, figures) of each template execution beings shown in the master notebook?

**Comment by bikashg** [comment]
I fail to see how this can be a normal output. In the template notebook, there is a statement `print('Result of analysis "%s" on dataset %d is %.3f.' % (analysis_type, data_id, result))`. If the master notebook is calling the template, then that code should be executed and print something.

**Comment by arc12** [comment]
@bikashg this all works for me. I suggest you study the README. The master notebook does not "call" the template; it copies it, inserts the parameters, then executes the copy, CREATING THE OUTPUT IN THE COPY.

**Comment by bikashg** [comment]
@arc12 : OK but do you see something printed somewhere? I don't see anything.

**Comment by tritemio** [comment]
Not an issue closing.
